[build]
# Use Python 3.11 for optimal AI/ML performance
providers = ["python"]

[variables]
# Python optimization for AI workloads
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
# Install system dependencies for AI/ML libraries
aptPackages = [
    "build-essential",
    "python3-dev",
    "libpq-dev",
    "postgresql-client",
    "curl",
    "git"
]

[phases.install]
# Install Python dependencies with AI optimizations
cmds = [
    "python3 -m pip install --upgrade pip setuptools wheel",
    "python3 -m pip install -r requirements-railway.txt"
]

[start]
# Start the medical platform
cmd = "python3 simple_main.py"

[env]
# Production environment settings
ENVIRONMENT = "production"
DEBUG = "false"
HOST = "0.0.0.0"
PORT = "$PORT"